SET SCHEMA 'zafira';

-- RabbitMQ
UPDATE INTEGRATIONS SET ENABLED=:RABBITMQ_ENABLED WHERE INTEGRATIONS.NAME='RABBITMQ';
UPDATE INTEGRATION_SETTINGS SET VALUE=:RABBITMQ_HOST FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='RABBITMQ_HOST';
UPDATE INTEGRATION_SETTINGS SET VALUE=:RABBITMQ_PORT FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='RABBITMQ_PORT';
UPDATE INTEGRATION_SETTINGS SET VALUE=:RABBITMQ_USERNAME FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='RABBITMQ_USER';
UPDATE INTEGRATION_SETTINGS SET VALUE=:RABBITMQ_PASSWORD FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='RABBITMQ_PASSWORD';

-- Jenkins Server
UPDATE INTEGRATIONS SET ENABLED=:JENKINS_ENABLED WHERE INTEGRATIONS.NAME='JENKINS';
UPDATE INTEGRATION_SETTINGS SET VALUE=:JENKINS_URL FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='JENKINS_URL';
UPDATE INTEGRATION_SETTINGS SET VALUE=:JENKINS_USER FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='JENKINS_USER';
UPDATE INTEGRATION_SETTINGS SET VALUE=:JENKINS_PASSWORD FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='JENKINS_API_TOKEN_OR_PASSWORD';
UPDATE INTEGRATION_SETTINGS SET VALUE=:JENKINS_FOLDER FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='JENKINS_FOLDER';
UPDATE INTEGRATION_SETTINGS SET VALUE=:JENKINS_JOB_URL_VISIBILITY FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='JENKINS_JOB_URL_VISIBILITY';

-- Storage Provider
UPDATE INTEGRATIONS SET ENABLED=:S3_ENABLED WHERE INTEGRATIONS.NAME='AMAZON';
UPDATE INTEGRATION_SETTINGS SET VALUE=:S3_BUCKET FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='AMAZON_BUCKET';
UPDATE INTEGRATION_SETTINGS SET VALUE=:S3_ACCESS_KEY FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='AMAZON_ACCESS_KEY';
UPDATE INTEGRATION_SETTINGS SET VALUE=:S3_SECRET_KEY FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='AMAZON_SECRET_KEY';
UPDATE INTEGRATION_SETTINGS SET VALUE=:S3_REGION FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='AMAZON_REGION';

-- Selenium Server
UPDATE INTEGRATIONS SET ENABLED=:SELENIUM_ENABLED WHERE INTEGRATIONS.NAME='SELENIUM';
UPDATE INTEGRATION_SETTINGS SET VALUE=:SELENIUM_URL FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='SELENIUM_URL';
UPDATE INTEGRATION_SETTINGS SET VALUE=:SELENIUM_USER FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='SELENIUM_USER';
UPDATE INTEGRATION_SETTINGS SET VALUE=:SELENIUM_PASSWORD FROM INTEGRATION_PARAMS WHERE INTEGRATION_SETTINGS.INTEGRATION_PARAM_ID=INTEGRATION_PARAMS.ID AND INTEGRATION_PARAMS.NAME='SELENIUM_PASSWORD';

