SELECT cron.schedule ('5 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TOTAL_VIEW$$);
SELECT cron.schedule ('1 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST32DAYS_VIEW$$);
SELECT cron.schedule ('0 7 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TEST_CASE_HEALTH_VIEW$$);
