SET SCHEMA 'zafira';
DELETE
FROM databasechangelog;
INSERT INTO databasechangelog(id,
                              author,
                              filename,
                              dateexecuted,
                              orderexecuted,
                              exectype)
VALUES ('001_create_modification_trigger',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('002_create_database',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('003_insert_default_data',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('004_create_views',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('005_create_widgets',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('006_add_default_launcher',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('007_update_jenkins_integration',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('008_update_mcloud_integration',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED'),
       ('009_update_selenium_integration',
        'itsvirko',
        'classpath:db/changelog.yml',
        current_timestamp,
        1,
        'EXECUTED');
DROP TABLE IF EXISTS GROUP_PERMISSIONS;
DROP TABLE IF EXISTS PERMISSIONS;
DROP TABLE IF EXISTS USER_GROUPS;
DROP TABLE IF EXISTS INVITATIONS;
DROP TABLE IF EXISTS GROUPS;

