SELECT cron.schedule ('0 0 1 * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TOTAL_VIEW$$);
SELECT cron.schedule ('0 7 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.THIRTY_DAYS_VIEW$$);
SELECT cron.schedule ('0 7 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TEST_CASE_HEALTH_VIEW$$);
