SET SCHEMA 'zafira';

INSERT INTO DASHBOARDS (TITLE, HIDDEN, POSITION, EDITABLE) VALUES ('General', FALSE, 0, FALSE);
INSERT INTO DASHBOARDS (TITLE, HIDDEN, POSITION, EDITABLE) VALUES ('Personal', TRUE, 1001, FALSE);
INSERT INTO DASHBOARDS (TITLE, HIDDEN, POSITION, EDITABLE) VALUES ('User Performance', TRUE, 1002, FALSE);
INSERT INTO DASHBOARDS (TITLE, HIDDEN, POSITION, EDITABLE) VALUES ('Stability', TRUE, 1003, FALSE);
INSERT INTO DASHBOARDS (TITLE, HIDDEN, POSITION, EDITABLE) VALUES ('Failures analysis', TRUE, 1004, FALSE);
